#!/bin/sh
set -e

ICON_NAME="kilo"

for size in 16 24 32 48 64 128 256; do
    SRC="/opt/kilo/product_logo_${size}.png"
    DST="/usr/share/icons/hicolor/${size}x${size}/apps/${ICON_NAME}.png"

    if [ -f "$SRC" ]; then
        mkdir -p "$(dirname "$DST")"
        install -m 0644 "$SRC" "$DST"
    fi
done


if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -f /usr/share/icons/hicolor || true
fi


update-desktop-database >/dev/null 2>&1 || true

if [ -f /opt/kilo/chrome_sandbox ]; then
    chown root:root /opt/kilo/chrome_sandbox
    chmod 4755 /opt/kilo/chrome_sandbox
fi

update_defaults_list() {
    DESKTOP_FILE="/usr/share/applications/$1"
    DEFAULTS_LIST="/usr/share/applications/defaults.list"

    [ ! -f "$DESKTOP_FILE" ] && return
    [ ! -f "$DEFAULTS_LIST" ] && return

    mime_types=$(grep '^MimeType=' "$DESKTOP_FILE" | cut -d= -f2 | tr ';' ' ')
    for mime in $mime_types; do
        if grep -q "^$mime=" "$DEFAULTS_LIST"; then
            if ! grep -q "^$mime=.*$1" "$DEFAULTS_LIST"; then
                old_apps=$(grep "^$mime=" "$DEFAULTS_LIST" | cut -d= -f2-)
                grep -v "^$mime=" "$DEFAULTS_LIST" > "${DEFAULTS_LIST}.new"
                echo "$mime=${old_apps};$1" >> "${DEFAULTS_LIST}.new"
                mv "${DEFAULTS_LIST}.new" "$DEFAULTS_LIST"
            fi
        else
            echo "$mime=$1;" >> "$DEFAULTS_LIST"
        fi
    done
}

update_defaults_list "kilo-browser.desktop"

GNOME_DFL_APPS=/usr/share/gnome-control-center/default-apps/gnome-default-applications.xml
if [ -f "$GNOME_DFL_APPS" ]; then
    if ! grep -q "kilo-browser.desktop" "$GNOME_DFL_APPS"; then
        sed -i \
          "/^[[:space:]]*<web-browsers>[[:space:]]*$/ r /opt/kilo/default-app-block" \
          "$GNOME_DFL_APPS"
    fi
fi

if [ ! -e /usr/bin/kilo ]; then
    ln -s /opt/kilo/kilo-desktop-wrapper /usr/bin/kilo
fi

exit 0
